apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpaca-prod
  labels:
    ver: "1"
    app: alpaca
    env: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      ver: "1"
      app: alpaca
      env: prod
  template:
    metadata:
      labels:
        ver: "1"
        app: alpaca
        env: prod
    spec:
      containers:
        - name: kuard
          image: artpropp/kuard-aarch64
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              port: 8080
              path: /ready
            periodSeconds: 2
            initialDelaySeconds: 0
            failureThreshold: 3
            successThreshold: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpaca-test
  labels:
    ver: "2"
    app: alpaca
    env: test
spec:
  replicas: 1
  selector:
    matchLabels:
      ver: "2"
      app: alpaca
      env: test
  template:
    metadata:
      labels:
        ver: "2"
        app: alpaca
        env: test
    spec:
      containers:
        - name: kuard
          image: artpropp/kuard-aarch64
          ports:
            - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bandicoot-prod
  labels:
    ver: "2"
    app: bandicoot
    env: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      ver: "2"
      app: bandicoot
      env: prod
  template:
    metadata:
      labels:
        ver: "2"
        app: bandicoot
        env: prod
    spec:
      containers:
        - name: kuard
          image: artpropp/kuard-aarch64
          ports:
            - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bandicoot-test
  labels:
    ver: "2"
    app: bandicoot
    env: test
spec:
  replicas: 1
  selector:
    matchLabels:
      ver: "2"
      app: bandicoot
      env: test
  template:
    metadata:
      labels:
        ver: "2"
        app: bandicoot
        env: test
    spec:
      containers:
        - name: kuard
          image: artpropp/kuard-aarch64
          ports:
            - containerPort: 8080
