apiVersion: batch/v1
kind: Job
metadata:
  name: oneshot
spec:
  parallelism: 5
  completions: 10
  template:
    metadata:
      labels:
        chapter: jobs
    spec:
      containers:
        - name: kuard
          image: artpropp/kuard-aarch64:green
          imagePullPolicy: Always
          args:
            - --keygen-enable
            - --keygen-exit-on-complete
            - --keygen-num-to-gen=10
      restartPolicy: OnFailure