apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: kuard
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kuard
        version: "2"
    spec:
      containers:
        - name: kuard
          image: artpropp/kuard-aarch64:latest
          ports:
            - containerPort: 8080

  selector:
    matchLabels:
      app: kuard
      version: "2"